export enum Categories {
    LTK_FIND = 'LTK Find',
    WINTER_TRENDS = 'Winter Trends',
    LTK_U = 'LTK-U',
    HOME = 'Home',
    DEAL_ALERT = 'Deal Alert',
    UNDER_50 = 'Under $50',
    UNDER_100 = 'Under $100',
    STYLE_TIPS = 'Style Tips',
    BEAUTY = 'Beauty',
    FITNESS = 'Fitness',
    CURVES = 'Curves',
    SHOPPABLE_VIDEO = 'Shoppable Video',
    WORKWEAR = 'Workwear',
    SWIM = 'Swim',
    TRAVEL = 'Travel',
    SHOE_CRUSHES = 'Shoe Crushes',
    IT_BAGS = 'It Bags',
    BABY = 'Baby',
    BUMP = 'Bump',
    KIDS = 'Kids',
    FAMILY = 'Family',
    MENS = 'Mens',
    WEDDINGS = 'Weddings',
    EUROPE = 'Europe',
    BRASIL= 'Brasil'
}
